# Site settings
title: MAI Minh
SEOTitle: MAI Minh | maiminh1996 | Nguyen Anh Minh MAI
header-img: img/home-bg.jpg
email: mainguyenanhminh1996@gmail.com
description: "Computer Science Blog | Nguyen Anh Minh MAI, Computer Vision Research Scientist"
keyword: "Computer Vision, Deep Learning, Machine Learning, python, C++, Java"
url: "https://maiminh1996.github.io/"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
# RSS: true
RSS: true

# weibo_username:     
# zhihu_username:     
github_username:    maiminh1996
twitter_username:   minh24035814
#facebook_username:  
linkedin_username:  nguyen-anh-minh-mai



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
# permalink: pretty
permalink: /:year/:month/:day/:title/
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json", "README.vi.md", "README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings
disqus_username: maiminh1996.github.io

# Netease settings
netease_comment: false



# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: 'G-HPVN42DG57'            # Format: UA-xxxxxx-xx
ga_domain: maiminh1996.github.io/



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Nguyen Anh Minh MAI <br> AI Research Engineer"
sidebar-avatar: https://avatars.githubusercontent.com/u/34424334?v=4 # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false
page-katex: false





# Friends
# friends: [
#     {
#     #     title: "Nguyen Thi Thuy Ha",
#     #     href: ""
#     # },{
        
#     },{
        
#     }
# ]
