code --install-extension alefragnani.Bookmarks
code --install-extension antfu.browse-lite
code --install-extension austin.code-gnu-global
code --install-extension bierner.markdown-preview-github-styles
code --install-extension ccls-project.ccls
code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension cschlosser.doxdocgen
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension donjayamanne.githistory
code --install-extension dracula-theme.theme-dracula
code --install-extension eamodio.gitlens
code --install-extension edwardhjp.vscode-author-generator
code --install-extension efoerster.texlab
code --install-extension esbenp.prettier-vscode
code --install-extension formulahendry.code-runner
code --install-extension foxundermoon.shell-format
code --install-extension GitHub.copilot
code --install-extension GitHub.vscode-pull-request-github
code --install-extension goessner.mdmath
code --install-extension Guyutongxue.cpp-reference
code --install-extension hediet.vscode-drawio
code --install-extension James-Yu.latex-workshop
code --install-extension jeff-hykin.better-cpp-syntax
code --install-extension josetr.cmake-language-support-vscode
code --install-extension KevinRose.vsc-python-indent
code --install-extension kriegalex.vscode-cudacpp
code --install-extension mathematic.vscode-latex
code --install-extension mhutchie.git-graph
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-dotnettools.vscode-dotnet-runtime
code --install-extension ms-python.isort
code --install-extension ms-python.pylint
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-toolsai.vscode-jupyter-cell-tags
code --install-extension ms-toolsai.vscode-jupyter-slideshow
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode-remote.vscode-remote-extensionpack
code --install-extension ms-vscode.cmake-tools
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.cpptools-extension-pack
code --install-extension ms-vscode.cpptools-themes
code --install-extension ms-vscode.remote-explorer
code --install-extension ms-vscode.remote-server
code --install-extension nickfode.latex-formatter
code --install-extension nvidia.nsight-vscode-edition
code --install-extension ritwickdey.LiveServer
code --install-extension Shan.code-settings-sync
code --install-extension steoates.autoimport
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension streetsidesoftware.code-spell-checker-vietnamese
code --install-extension TabNine.tabnine-vscode
code --install-extension tchojnacki.cpp-compile
code --install-extension techer.open-in-browser
code --install-extension tomoki1207.pdf
code --install-extension torn4dom4n.latex-support
code --install-extension twxs.cmake
code --install-extension Tyriar.luna-paint
code --install-extension VisualStudioExptTeam.intellicode-api-usage-examples
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vomout.latex-syntax
code --install-extension vscode-icons-team.vscode-icons
code --install-extension wayou.vscode-todo-highlight
code --install-extension wix.vscode-import-cost
code --install-extension yzane.markdown-pdf
